Updated Installation Instructions
xCollateral/VulkanMod pull request #315
Opened 2023-10-01 22:12 UTC by maingotj

Updated Installation Instructions for the forge mod loader by adding a link to the download page and additional instructions on how to configure the download. Added clarification for where to move the VulkanMod.jar and how to do it. Additionally added multiple formatting tweaks such as left aligning the bottom and deleting a duplicate download link.

2023-10-11 01:21 UTC, iMonZ requested changes

2023-10-11 01:21 UTC, iMonZ commented on README.md
> +Proceed through all of these steps to correctly install the Vulcan mod to your Windows device
```suggestion
Proceed through all of these steps to correctly install the Vulkan mod to your device
```

1. Vulkan is wrongly written
2. This mod is not only for Windows

2023-10-11 01:22 UTC, iMonZ commented on README.md
> +1. Once on the page click the blue "download for Windows" button
Again Same issue

2023-10-11 01:23 UTC, iMonZ commented
Thanks but this tutorial is only for MS-Windows.
So how about we rebrand it like that since other OSes having different installation methods.

2024-04-09 20:43 UTC, xCollateral commented
Since there are no meaningful and we are  working on #383, I'll close this PR.

2024-04-09 20:43 UTC, closed without merging